FROM nginx:alpine

# Copy all the static frontend files to the default NGINX public HTML directory
COPY . /usr/share/nginx/html

# Expose port 80 inside the container
EXPOSE 80

# NGINX runs automatically when the container starts
